### ISSUE TITLE
What happened to the Tidy Server List?

### ISSUE THREAD

**Issue by LotteBestGirl** [qwerasd205/BetterDiscordV2Plugins#1]
I used that theme a lot in 2017, but now i search for it here and it's 404, what happened?

**Comment by qwerasd205** [comment]
Sorry, but a recent Discord update broke this theme so I just removed any last traces of it yesterday, additionally this repository is for _plugins_ for BD _v2_ and as such would not contain it. I had not realized that anyone was really using the theme but now that I do I'll go ahead and update the theme and release it again. When I do I will respond to this issue with a link and close it.

**Comment by qwerasd205** [comment]
https://qwerasd205.github.io/CompactServerList
There you go, enjoy! :) Have a nice day.

**Comment by LotteBestGirl** [comment]
Oh, didnt notice that some themes we're broken because of that redesign...

Anyways, thanks for rewritting it man :)
